name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    environment: prod-cd
    runs-on: ubuntu-latest
    permissions:
      # Required for creating releases and tags
      contents: write
      # Required for OIDC/Provenance
      id-token: write
      # Required for creating PRs
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
          cache-dependency-path: "yarn.lock"

      # Upgrade npm since trusted publishing requires npm CLI version 11.5.1 or later
      - name: Upgrade npm
        run: npm install -g npm@^11.5.1

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          version: yarn run version
          publish: yarn run release
          commit: 'ci(changesets): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b #2.5.0
        with:
          draft: false
          tag_name: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          name: Release v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}

